schemas = [
  "agp_aggregations",
  "anomaly_detection",
  "atlas_rawdata",
  "bohdan_bashuk_q31v_da_mlp",
  "dataengineering_sandbox",
  "datascience",
  "datascience_sandbox",
  "default",
  "fyber_bi",
  "fyber_bi_utils",
  "fyber_billing",
  "lakehouse",
  "lakehouse_dimensions",
  "lakehouse_reporting",
  "lakehouse_views",
  "reporting_sandbox",
  "unity_catalog_migration"
]